name: Windows Build and Release

on:
  push:
    tags:
      - 'v*'  # Только при пуше тега, например v1.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Extract CMake project name
        id: cmake_project
        shell: pwsh
        run: |
          $content = Get-Content CMakeLists.txt
          foreach ($line in $content) {
            if ($line -match '^project\(([^)]+)\)') {
              echo "name=$($matches[1])" >> $env:GITHUB_OUTPUT
              break
            }
          }

      - name: Create build directory
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Copy executable to release folder
        shell: pwsh
        run: |
          $exePath = "build\\Release\\${{ steps.cmake_project.outputs.name }}.exe"
          if (-Not (Test-Path $exePath)) {
            Write-Error "Executable not found: $exePath"
          }
          New-Item -ItemType Directory -Force -Path release
          Copy-Item -Path $exePath -Destination "release\\${{ steps.cmake_project.outputs.name }}.exe"

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
