name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Extract CMake project name
        id: cmake_project
        shell: bash
        run: |
          name=$(grep -Po '^project\(\K[^)]*' CMakeLists.txt)
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Create build directory
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Copy executable to release folder
        shell: pwsh
        run: |
          $exePath = "build\\Release\\${{ steps.cmake_project.outputs.name }}.exe"
          if (-Not (Test-Path $exePath)) {
            Write-Error "Executable not found: $exePath"
          }
          New-Item -ItemType Directory -Force -Path release
          Copy-Item -Path $exePath -Destination "release\\${{ steps.cmake_project.outputs.name }}.exe"

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cmake_project.outputs.name }}-windows
          path: release/*.exe
